import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { SDK_VERSION } from '../../../connect/version';

/**
 * connect/version.ts is AUTO-GENERATED by scripts/gen-version.mjs on `prebuild`, so a
 * plain `npm install` of a `file:` dependency never regenerates it. When it drifts, the
 * handshake advertises a wrong sdkVersion and a wallet with a minSdkVersion floor rejects
 * the dApp with UNSUPPORTED_PROTOCOL_VERSION 4007 — a failure nobody traces back to a
 * stale generated constant.
 *
 * When this fails: run `node scripts/gen-version.mjs` and commit connect/version.ts.
 *
 * This test is a DEVELOPER convenience, not the CI gate. In CI, `npm run build` (whose
 * `prebuild` regenerates this file) runs before `npm run test:run`, so by the time the
 * suite executes the file has already been fixed on disk. The real gate is the
 * `verify:version` script, wired into ci.yml BEFORE the Build step.
 *
 * package.json is read from disk rather than imported so this test does not depend on
 * resolveJsonModule or on the bundler's JSON handling.
 */
describe('connect/version.ts', () => {
  it('matches package.json version', () => {
    const pkgPath = fileURLToPath(new URL('../../../package.json', import.meta.url));
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { version: string };
    expect(SDK_VERSION).toBe(pkg.version);
  });
});
