// scripts/gen-version.mjs — writes connect/version.ts from package.json. Runs on prebuild.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const out = resolve(root, 'connect/version.ts');
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.\nexport const SDK_VERSION = '${version}';\n`,
);
console.log(`[gen-version] wrote connect/version.ts (SDK_VERSION='${version}')`);
