/**
 * Profile Aggregator Pointer Layer — error taxonomy (SPEC §12, v3.5).
 *
 * 27 codes total: 26 AGGREGATOR_POINTER_* + 1 SECURITY_ORIGIN_MISMATCH.
 */

export const AggregatorPointerErrorCode = {
  CONFLICT: 'AGGREGATOR_POINTER_CONFLICT',
  STALE: 'AGGREGATOR_POINTER_STALE',
  CORRUPT: 'AGGREGATOR_POINTER_CORRUPT',
  NOT_FOUND: 'AGGREGATOR_POINTER_NOT_FOUND',
  PARTIAL: 'AGGREGATOR_POINTER_PARTIAL',
  REJECTED: 'AGGREGATOR_POINTER_REJECTED',
  RETRY_EXHAUSTED: 'AGGREGATOR_POINTER_RETRY_EXHAUSTED',
  CID_TOO_LARGE: 'AGGREGATOR_POINTER_CID_TOO_LARGE',
  VERSION_OUT_OF_RANGE: 'AGGREGATOR_POINTER_VERSION_OUT_OF_RANGE',
  DISCOVERY_OVERFLOW: 'AGGREGATOR_POINTER_DISCOVERY_OVERFLOW',
  NETWORK_ERROR: 'AGGREGATOR_POINTER_NETWORK_ERROR',
  UNTRUSTED_PROOF: 'AGGREGATOR_POINTER_UNTRUSTED_PROOF',
  UNREACHABLE_RECOVERY_BLOCKED: 'AGGREGATOR_POINTER_UNREACHABLE_RECOVERY_BLOCKED',
  MARKER_CORRUPT: 'AGGREGATOR_POINTER_MARKER_CORRUPT',
  CAR_TOO_LARGE: 'AGGREGATOR_POINTER_CAR_TOO_LARGE',
  CAR_FETCH_TIMEOUT: 'AGGREGATOR_POINTER_CAR_FETCH_TIMEOUT',
  CAR_UNAVAILABLE: 'AGGREGATOR_POINTER_CAR_UNAVAILABLE',
  CORRUPT_STREAK: 'AGGREGATOR_POINTER_CORRUPT_STREAK',
  SECURITY_ORIGIN_MISMATCH: 'SECURITY_ORIGIN_MISMATCH',
  UNSUPPORTED_RUNTIME: 'AGGREGATOR_POINTER_UNSUPPORTED_RUNTIME',
  PUBLISH_BUSY: 'AGGREGATOR_POINTER_PUBLISH_BUSY',
  TRUST_BASE_STALE: 'AGGREGATOR_POINTER_TRUST_BASE_STALE',
  CAR_UNEXPECTED_ENCODING: 'AGGREGATOR_POINTER_CAR_UNEXPECTED_ENCODING',
  AGGREGATOR_REJECTED: 'AGGREGATOR_POINTER_AGGREGATOR_REJECTED',
  PROTOCOL_ERROR: 'AGGREGATOR_POINTER_PROTOCOL_ERROR',
  WALKBACK_FLOOR: 'AGGREGATOR_POINTER_WALKBACK_FLOOR',
  CAPABILITY_DENIED: 'AGGREGATOR_POINTER_CAPABILITY_DENIED',
} as const;

export type AggregatorPointerErrorCodeType =
  (typeof AggregatorPointerErrorCode)[keyof typeof AggregatorPointerErrorCode];

export class AggregatorPointerError extends Error {
  public readonly code: AggregatorPointerErrorCodeType;
  public readonly details?: Record<string, unknown>;

  constructor(
    code: AggregatorPointerErrorCodeType,
    message?: string,
    details?: Record<string, unknown>,
    options?: { cause?: unknown },
  ) {
    super(message ?? code, options);
    this.name = 'AggregatorPointerError';
    this.code = code;
    this.details = details;
  }
}
